export const chartSettings = {
  barChart: {
    scheme: 'vivid',
    xViewSize: 1050,
    yViewSize: 350,
    xAxisLabel: 'Year',
    showXAxisLabel: true,
    xAxis: true,
    yAxisLabel: 'Amount (£)',
    showYAxisLabel: true,
    yAxis: true,
    legendPosition: 'below',
    legendTitle: '',
    legend: true,
    gradient: true,
  },
  lineChart: {
    scheme: 'vivid',
    xViewSize: 1150,
    yViewSize: 350,
    xAxisLabel: 'Date',
    showXAxisLabel: true,
    xAxis: true,
    yAxisLabel: 'Amount (£)',
    showYAxisLabel: true,
    yAxis: true,
    legendPosition: 'below',
    legendTitle: '',
    legend: false,
  },
};
